name: Hello World

on:
    pull_request:
        branches: 
            - main
        types: 
            - opened
            - reopened

permissions:
    pull-requests: write

jobs:
    write_hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Comment PR
              uses: thollander/actions-comment-pull-request@v1
              with:
                message: 'Thank you for your pull request!'
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                reactions: rocket
